<?php

namespace Proxies\__CG__\INCES\ComedorBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \INCES\ComedorBundle\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'INCES\\ComedorBundle\\Entity\\Usuario' . "\0" . 'id', '' . "\0" . 'INCES\\ComedorBundle\\Entity\\Usuario' . "\0" . 'nombre', '' . "\0" . 'INCES\\ComedorBundle\\Entity\\Usuario' . "\0" . 'apellido', '' . "\0" . 'INCES\\ComedorBundle\\Entity\\Usuario' . "\0" . 'cedula', '' . "\0" . 'INCES\\ComedorBundle\\Entity\\Usuario' . "\0" . 'ncarnet', '' . "\0" . 'INCES\\ComedorBundle\\Entity\\Usuario' . "\0" . 'a_i', '' . "\0" . 'INCES\\ComedorBundle\\Entity\\Usuario' . "\0" . 'correo', '' . "\0" . 'INCES\\ComedorBundle\\Entity\\Usuario' . "\0" . 'image', '' . "\0" . 'INCES\\ComedorBundle\\Entity\\Usuario' . "\0" . 'rol', '' . "\0" . 'INCES\\ComedorBundle\\Entity\\Usuario' . "\0" . 'usuario_menus');
        }

        return array('__isInitialized__', '' . "\0" . 'INCES\\ComedorBundle\\Entity\\Usuario' . "\0" . 'id', '' . "\0" . 'INCES\\ComedorBundle\\Entity\\Usuario' . "\0" . 'nombre', '' . "\0" . 'INCES\\ComedorBundle\\Entity\\Usuario' . "\0" . 'apellido', '' . "\0" . 'INCES\\ComedorBundle\\Entity\\Usuario' . "\0" . 'cedula', '' . "\0" . 'INCES\\ComedorBundle\\Entity\\Usuario' . "\0" . 'ncarnet', '' . "\0" . 'INCES\\ComedorBundle\\Entity\\Usuario' . "\0" . 'a_i', '' . "\0" . 'INCES\\ComedorBundle\\Entity\\Usuario' . "\0" . 'correo', '' . "\0" . 'INCES\\ComedorBundle\\Entity\\Usuario' . "\0" . 'image', '' . "\0" . 'INCES\\ComedorBundle\\Entity\\Usuario' . "\0" . 'rol', '' . "\0" . 'INCES\\ComedorBundle\\Entity\\Usuario' . "\0" . 'usuario_menus');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido($apellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido', array($apellido));

        return parent::setApellido($apellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido', array());

        return parent::getApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setCedula($cedula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCedula', array($cedula));

        return parent::setCedula($cedula);
    }

    /**
     * {@inheritDoc}
     */
    public function getCedula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCedula', array());

        return parent::getCedula();
    }

    /**
     * {@inheritDoc}
     */
    public function setNcarnet($ncarnet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNcarnet', array($ncarnet));

        return parent::setNcarnet($ncarnet);
    }

    /**
     * {@inheritDoc}
     */
    public function getNcarnet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNcarnet', array());

        return parent::getNcarnet();
    }

    /**
     * {@inheritDoc}
     */
    public function setAI($aI)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAI', array($aI));

        return parent::setAI($aI);
    }

    /**
     * {@inheritDoc}
     */
    public function getAI()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAI', array());

        return parent::getAI();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreo($correo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreo', array($correo));

        return parent::setCorreo($correo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreo', array());

        return parent::getCorreo();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setRol(\INCES\ComedorBundle\Entity\Rol $rol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRol', array($rol));

        return parent::setRol($rol);
    }

    /**
     * {@inheritDoc}
     */
    public function getRol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRol', array());

        return parent::getRol();
    }

    /**
     * {@inheritDoc}
     */
    public function __tostring()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__tostring', array());

        return parent::__tostring();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsuarioMenu(\INCES\ComedorBundle\Entity\UsuarioMenu $usuarioMenus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsuarioMenu', array($usuarioMenus));

        return parent::addUsuarioMenu($usuarioMenus);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioMenus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioMenus', array());

        return parent::getUsuarioMenus();
    }

}
